
import React from 'react';

interface Props {
  onBack: () => void;
}

const HowItWorks: React.FC<Props> = ({ onBack }) => {
  return (
    <div className="min-h-screen bg-background-dark font-display text-white">
      <nav className="border-b border-border-dark bg-background-dark/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-[1280px] mx-auto px-6 py-4 flex items-center justify-between">
          <button onClick={onBack} className="flex items-center gap-2 group">
            <span className="material-symbols-outlined group-hover:-translate-x-1 transition-transform">arrow_back</span>
            <span className="font-bold">Back</span>
          </button>
          <h1 className="text-xl font-bold tracking-tight">How It Works</h1>
          <div className="w-10"></div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto p-6 md:p-20 space-y-16">
        <section className="text-center space-y-4">
          <h2 className="text-5xl font-bold tracking-tight">Digital Magic for the Real World</h2>
          <p className="text-gray-400 text-lg">Understand the technological process behind our 3D transformations.</p>
        </section>

        <div className="space-y-24">
          {[
            {
              step: '01',
              title: 'Photographic Capture',
              desc: 'Take photos of the object from various angles. The better the lighting and sharpness, the higher the precision of the 3D mesh generated by our AI.',
              icon: 'photo_camera',
              img: '/images/how-it-works/step1.png'
            },
            {
              step: '02',
              title: 'Neural Processing',
              desc: 'Our servers equipped with cutting-edge GPUs process your images, calculating depth points and reconstructing volumetric textures.',
              icon: 'memory',
              img: '/images/how-it-works/step2.png'
            },
            {
              step: '03',
              title: 'Optimization & Mesh',
              desc: 'The AI automatically corrects gaps in the geometry and simplifies the mesh (decimation) to ensure the file is lightweight and compatible with any software.',
              icon: 'grid_view',
              img: '/images/how-it-works/step3.png'
            },
            {
              step: '04',
              title: 'Export & Use',
              desc: 'Download your model in GLB for web, OBJ for editing, or STL ready for your 3D printer. The world is the limit!',
              icon: 'print',
              img: '/images/how-it-works/step4.png'
            }
          ].map((item, i) => (
            <div key={i} className={`flex flex-col ${i % 2 === 0 ? 'md:flex-row' : 'md:flex-row-reverse'} gap-12 items-center`}>
              <div className="flex-1 space-y-6">
                <div className="text-6xl font-black text-primary/20">{item.step}</div>
                <div className="flex items-center gap-4">
                  <span className="material-symbols-outlined text-primary text-4xl">{item.icon}</span>
                  <h3 className="text-3xl font-bold">{item.title}</h3>
                </div>
                <p className="text-gray-400 text-lg leading-relaxed">{item.desc}</p>
              </div>
              <div className="flex-1 w-full">
                <div className="bg-surface-dark border border-border-dark rounded-3xl overflow-hidden shadow-2xl">
                  <img src={item.img} alt={item.title} className="w-full aspect-video object-cover opacity-60" />
                </div>
              </div>
            </div>
          ))}
        </div>

        <section className="bg-primary/10 border border-primary/20 p-12 rounded-[3rem] text-center space-y-6">
          <h3 className="text-3xl font-bold">Ready to start?</h3>
          <p className="text-gray-300 max-w-lg mx-auto">Transform your first photo now and discover the power of our AI.</p>
          <button className="bg-primary hover:bg-primary/90 transition-all px-10 py-4 rounded-2xl font-black uppercase tracking-widest text-xs">Start Transformation</button>
        </section>
      </main>
    </div>
  );
};

export default HowItWorks;
